### ISSUE TITLE
add -s parameter to ensure energy-sorted output

### ISSUE THREAD

**Issue by martin-raden** [BackofenLab/IntaRNA#109]
parameter has to take a single or a comma-separated list of CSV column ids for sorting. the list is used for tie-breaking.

**Comment by martin-mann** [comment]
ensure that InteractionEnergy instances are not deleted, before final output ist produced!

**Comment by martin-raden** [comment]
implemented in 64d5ac90d51e875ce6506e5e353f0913c7030a61
