### ISSUE TITLE
test: performance of VRNA > or < 2.4.0

### ISSUE THREAD

**Issue by martin-raden** [BackofenLab/IntaRNA#111]
since heavy changes in window-based accessibility prediction output

to the better or to the worse?

**Comment by martin-mann** [comment]
mail Baard if checked

**Comment by martin-mann** [comment]
this boils down to the following, which result in the same output
```[bash]
VRNA-2.3.5/RNAplfold -W 150 -L 99 -u 10
VRNA-2.4.*/RNAplfold -W 150 -L 100
```
Thus, the usage of VRNA-2.3.5 will use a base pair span `+1`, which does alter the unpaired probs for longer sequences.

**Comment by martin-mann** [comment]
=> therefore: an optimization of W/L is interesting? huuuhhh... not again. ;)

**Comment by mmiladi** [comment]
@martin-mann Removed the project :laughing: ... :clap:

**Comment by mmiladi** [comment]
What are these heavy changes? Is it related to the issue Ronny fixed for plfold-SHAPE +1 position?

**Comment by martin-mann** [comment]
@mmiladi the definition of base pair span was unified, which either adds or removes the maximal base pairs from the RNAplfold computation and thus might shift the probabilities, since stronger local structures are possible (longer helices), see [VRNA Changelog v2.4.0](https://www.tbi.univie.ac.at/RNA/changelog.html#v240). but it seems some other changes occured as well, since I couldnt reproduce the same unpaired files by just L+1 for a long input sequence provided by a user..

**Comment by mmiladi** [comment]
Thanks for the info! Is the irreproducible case for unconstrained folding ?

**Comment by martin-mann** [comment]
the following plot shows, that the performance (for a genome wide prediction) is reduced...
![intarna-vrna](https://user-images.githubusercontent.com/22291305/41976518-9ea33610-7a1d-11e8-9441-e0014507afa6.jpg)

and it seems to get even worse with recent versions.. :cry:

**Comment by mmiladi** [comment]
@martin-mann How about benchmarking all 2.4.X versions to track specific bump that causes this performance reduction?

**Comment by martin-mann** [comment]
@mmiladi good point

@RickGelhausen are you willing to check this? that is, running the above benchmark for vrna 2.4.1-6 (or stop when a version equals 2.4.7)

**Comment by martin-mann** [comment]
ping @raumzeit : seems there is some change inbetween 2.4.0 and 2.4.7 that cause a (minor) performance reduction for IntaRNA in its benchmark. anything that pops to your mind?

**Comment by RickGelhausen** [comment]
@martin-mann: yes, I will set up the benchmark accordingly.

**Comment by RaumZeit** [comment]
@martin-mann I don't recall any changes but this last change with 2.4.8 for the interior loops (assuming, 
you only use the V3.0 API, i.e. functions with `vrna_` prefix).

Though, with version 2.4.2, there have been some corrections with respect to the individual loop-type dependent unpaired probabilities.This, however, is only relevant, if you pass the `VRNA_PROBS_WINDOW_UP_SPLOT` flag to the `vrna_probs_window()` funtion.

Also, `RNAplfold` and the underlying algorithms have been adapted to full hard constraints support with version 2.4.2 as well. But you don't use hard constraints, or do you?

You may also want to have a look at the diff for `LPfold.c` between v2.4.0 and v2.4.8: https://github.com/ViennaRNA/ViennaRNA/compare/v2.4.0...v2.4.8

**Comment by martin-mann** [comment]
Hi @RaumZeit ,
Rick did the screen and it seems there is a drop between v2.4.2 and 2.4.3 ?!
![intarna-vrna-screen](https://user-images.githubusercontent.com/22291305/42158533-fb672114-7df0-11e8-919a-eeabd03b931b.jpg)
any idea?

**Comment by martin-mann** [comment]
PS. we are only using the local folding routines ala RNAplfold

**Comment by martin-mann** [comment]
it seems, there were some local folding changes in https://github.com/ViennaRNA/ViennaRNA/compare/v2.4.0...v2.4.8
concerning
- dangling end handling
- scaling factors
- ... ?

**Comment by RaumZeit** [comment]
that's right, in particular, we applied some corrections in the RNAplfold related computations for multibranch loop contributions between release 2.4.2 and 2.4.3.
I strongly believe that the changes are necessary and implemented correctly, thus it seems odd that you see a drop in performance of IntaRNA. What are the units for the true positive deviation?
