### ISSUE TITLE
Streamed interaction prediction

### ISSUE THREAD

**Issue by martin-mann** [BackofenLab/IntaRNA#12]
to enable streamed interaction prediction (eg for large genomes) to reduce memory consumption:
- [x] compute optimal interactions within index ranges for both sequences
- [ ] initialize accessibility data for a given ranges for both sequences
- [ ] window-size dependent optimal interaction screen

**Comment by martin-mann** [comment]
can also be done as a first step via overlapping region decomposition that is parallelized

**Comment by mmiladi** [comment]
@martin-mann Cool! Would this also cover storing/caching the vrna computations like accessibilities in a file? 
I think it might be very useful for the scenarios where the genome is fixed and each run the user asks for interaction prediction between custom ranges of the genome. 
A very abstract example: in the first run pre-computations are done and stored in file for genome `hg38`. In the next run user provides ranges e.g. `chr1:1000-2000` & `chr12:500-1000`

**Comment by martin-mann** [comment]
genome Pu/AccED values can already be read from /stored to file via the `--out` and `--qAccFile` arguments, see [docu here](https://github.com/BackofenLab/IntaRNA#accessibility). this also supports multi-sequence input as your example suggests. you can also restrict your predictions to a subset of the input sequences (here something like `--tSubSet=1-1,12-12`).

what is *not* supported yet is the definition of ranges for individual sequences from a multi-sequence input. range definitions are currently only available for single-sequence input to keep the interface simple. but given your 'encoding', it might be possible to enable this for multi-sequence input as well.. will think about it! unfortunately, this is either blowing up the coding or requires a few central restructurings, both leading to additional work.. 😄 

what I am currently implementing is an automatic decomposition of the input sequence into overlapping regions of a given length (which will also be available for multi-sequence input). this enables parallelized predictions for the regions and can be combined eg with the subset feature from above (when talking about transcriptome data).

**Comment by mmiladi** [comment]
@martin-mann  Thanks for providing the details!
I also think better to not blow-up interface with special use-cases. A custom python pre-processing should be much simpler to develop than the core code :-)

**Comment by martin-mann** [comment]
the window-based prediction is now implemented in commit 655745f063c5c7dc83d33626223d065c046d2604 to be part release version 2.3.0 #128

**Comment by martin-mann** [comment]
I guess the accessibility data (linear) is not causing major memory issues in contrast to the quadratic memory consumption of the computations. thus, I will skip further development for this issue
