### ISSUE TITLE
Recapitulate sRNA/mRNA regions figure

### ISSUE THREAD

**Issue by dgelsin** [BackofenLab/IntaRNA#151]
Hello,

Is it possible to recreate the sRNA regions interaction figure generated from the html site using the command line output generated by --outMode=C? If so, what are the relevant columns to plot?

Below is an example of the figure I am talking about:

https://drive.google.com/file/d/1neNPcvmJB1KGOPP3VvHzgGyv8nhExJkw/view?usp=sharing

Thank you,

Diego

**Comment by martin-raden** [comment]
Hi @dgelsin 

the short answer is: not out of the box...

the long answer: the only underlying data is eventually the `start2,end2` information (given that the sRNAs are provided as `query` input)

the plot itself is created by some R-script written by a co-worker who left science meanwhile.. I will have a look if I can dig out the respective source code snippet.

Best,
Martin

**Comment by dgelsin** [comment]
Hi @martin-raden 

I think I actually was able to figure it out after I posted this ha.

Essentially, the figure is a density plot and a dumbbell plot. I averaged the `start2,end2` information and plotted that as a density plot `ggplot2 geom_density`. Then I made a dumbbell plot `ggplot2 geom_dumbbell`, again with `start2,end2` plotting the distance between the two coordinates. It gives a plot like this: https://drive.google.com/file/d/1US_hLKdDZMaLPetYZLemJ2qHmQgqpHKi/view?usp=sharing

You can do the same thing for the mRNA plots with `start1,end1`

Hope that helps others.

**Comment by martin-raden** [comment]
Hi @dgelsin 

many thanks for the update! If you have time, could you post a code snippet for the plotting? That would be supercool! 

Eventually, I would like to provide exactly what you inquired: a small script that takes IntaRNA CSV output and produces the plot. So your sample code (or even a pull request with a first draft of such a script) would be most welcome!

Thanks and have a nice weekend,
Martin

**Comment by dgelsin** [comment]
Hi Martin,

Apologies for the very late reply, but if you are still interesting in implementing this here is my guide/code:

**Density & dumbbell plots for sRNA-mRNA interaction visualization**
1. Do IntaRNA and get output table of all interactions

2. Make a table that is the average of start2,end2 in column2 and then column 3 is start2, and column 3 is end2, and column 4 is the putative target names

3. Load table in R"
`sRNA_interaction_table= read.table('intaRNA_interaction_data.txt')`

4. Check table for header names:
head(sRNA_interaction_table)
`V1`	`V2`	`V3`	`V4`
`21`	`16`	`26`	`HVO_RS0001`
...

5. Load dependencies in R for plots
`library(ggplot2)`
`library(ggalt)`
`library(cowplot)`

#####For sRNA plots
6. Make a density plot using table data, including a vertical line at the maxima
`ggplot(sRNA_interaction_table, aes(x=V1)) + geom_density() + scale_y_continuous(expand = c(0, 0), limits=c(0,0.0013))+scale_x_continuous(breaks=c(1,250,500,1000,1500,2000,2500),expand = c(0, 0),limits=c(0,2500)) +geom_vline(aes(xintercept= density(sRNA_interaction_table$V1)$x[116])) +theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank())`

7. Make a dumbbell plot using table data
`ggplot(sRNA_interaction_table, aes(x=V2,xend=V3,y=V4)) + geom_dumbbell(color="dodgerblue", size=2) + scale_x_continuous(breaks=c(1,25,50,75,100,125,130),expand = c(0, 0), limits=c(0,130)) +ylab("Putative Targets") +xlab("sRNA Length (nt)") + scale_y_discrete(position = "right") + theme(panel.grid.major.y=element_line(size=0.7,color="lightgray"),axis.text.y=element_blank())`

8. Combine density and dumbbell plots
`plot_grid(itsRNA_140475.2_sRNA_density_plot, itsRNA_140475.2_sRNA_dumbbell_plot,nrow=2,ncol=1,align = 'v')`


####Note: You can do the same thing for the mRNA plots with start1,end1

**Comment by martin-raden** [comment]
Hi @dgelsin 
you are my star! many thanks! If fine for you, I will make it a single R script and add it to the repo as postprocessing script!

:+1: 
Martin

**Comment by dgelsin** [comment]
Hi Martin,

Yes, that's great, go for it! Let me know if there is anything I can do to help.

-Diego

**Comment by dgelsin** [comment]
One thing to note is that you may only want to plot gene interactions <0.05 p-value or some type of metric like that.

**Comment by martin-raden** [comment]
Hi @dgelsin 
I condensed a generic R script from your code and have added it to the repository

https://github.com/BackofenLab/IntaRNA/blob/dev/R/README.md

feel free to comment and extend. :)

again, many thanks for the contribution!

best,
Martin

**Comment by martin-raden** [comment]
implemented in dev branch
