### ISSUE TITLE
Most recent conda release is not compiled with multithread support

### ISSUE THREAD

**Issue by BlueDrink9** [BackofenLab/IntaRNA#162]
This may be intentional, but in the current conda release `--threads` is not a valid option.

**Comment by martin-raden** [comment]
Hi @BlueDrink9 
as far as I am aware this only holds for the osx build the linux package should be available with multi-threading.
will have a look after my vacations.. :/
best,
Martin

**Comment by BlueDrink9** [comment]
Ah, you're probably correct. I'm using the OSX build.

Thanks for the prompt response, no hurry. I'll just compile it myself

**Comment by martin-raden** [comment]
Hi @BlueDrink9 

I enable multi-threading within the last conda package (v3.1.02).
Would you be so kind to check whether this is working, since I have no OSX platform at hand..

Many thanks,
Martin

**Comment by BlueDrink9** [comment]
```
$ intarna --version
    IntaRNA 3.1.0.2
    using Vienna RNA package 2.4.13 and boost 1.70.0
$ intarna --threads
    # ERROR : unrecognised option '--threads' : run with '--help' for allowed arguments
```
On linux with multithreaded conda, the error was that `# ERROR : the required argument for option '--threads' is missing : run with '--help' for allowed arguments`

Compiling it myself with libomp was pretty tricky iirc, and required the conda version of the clang compiler, as well as some custom build flags - although that was also probably hindered by my messy build environment.

I personally don't need this any more, if you don't want to add extra work to your plate right now.

**Comment by martin-raden** [comment]
Many thanks for testing.. mhh..
looks weird since it should (a) use VRNA 2.4.14 and (b) provide the 'threads' parameter.. :/
Will have to find somebody with an osx to play around. ;)

the linux error message is fine, since you didnt specify how many threads you want to use (a number >=0)

again, thanks for spending time looking into this!
Martin

**Comment by BlueDrink9** [comment]
Yeah, I just included the linux message to demo that the error on OSX *wasn't* because of not specifying thread number.

**Comment by BlueDrink9** [comment]
Ask me again in a month and I'll be happy to collab to get this working. Least I can do after using the software
