### ISSUE TITLE
Attaching IntaRNA docker container to VS Code

### ISSUE THREAD

**Issue by olive004** [BackofenLab/IntaRNA#207]
Hi,

I am using one of the latest IntaRNA docker containers (quay.io/biocontainers/intarna:3.3.2--pl5321h7ff8a90_0) on my Ubuntu 22.04 PC. The container is working fine in the shell both in my terminal and in VS Code, but for some reason when I try to attach the running container to VS Code I get a missing library error for libstdc++.so.6, despite the library being installed on my PC. I am using VS Code's Remote Explorer to attach the container.

Here is some of the output of my error
```
Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-b4701e0f9cf2dc42c1f9b3c505d60fa6f011ec1f.js' >/tmp/vscode-remote-containers-server-b4701e0f9cf2dc42c1f9b3c505d60fa6f011ec1f.js_1668445022697
Start: Run in Container: /bin/sh -lic echo -n f9f414114a8873493c2e585a6a0b07b8; cat /proc/self/environ; echo -n f9f414114a8873493c2e585a6a0b07b8
Container server: /root/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/node: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
Exit code 127
```

and here is my Dockerfile:
```
# syntax=docker/dockerfile:1

FROM quay.io/biocontainers/intarna:3.3.2--pl5321h7ff8a90_0
```

I get the same error when I pull other docker images that are hosted on Quay. Other containers (eg. Docker's ubuntu image) work fine. Wondering if the library is missing within IntaRNA somehow?

If anyone has any ideas for using a debugger within the docker container in some other way, that would be very helpful!

**Comment by olive004** [comment]
The hacky fix ended up being easy - the library libstdc++.so.6 already exists on the IntaRNA image, but not in the place VS Code looks for it. Finding the path to libstdc++.so.6 and simply copying it to the location it should have on Ubuntu / whichever linux distribution VS Code is using solves the issue.

**Comment by martin-raden** [comment]
@olive004 thanks for coming back to us with a solution to your problem!

👍 highly appreciated!

Best,
Martin
