### ISSUE TITLE
Add swig bindings

### ISSUE THREAD

**Issue by bgruening** [BackofenLab/IntaRNA#21]
It would be nice to have http://www.swig.org integration so that no one ever needs to wrap it into her/his preferred scripting language.

**Comment by martin-mann** [comment]
@bgruening should this be added enabled for all classes/modules or for the main preditor only? I guess I already know the answer... ;)

**Comment by bgruening** [comment]
Let's start with the main entry point and get the integration in place. We can extend it later on easily.
