### ISSUE TITLE
Conda command line and web based do not show the same output result

### ISSUE THREAD

**Issue by paolabc** [BackofenLab/IntaRNA#216]
Hi Everyone!

I am performing the analysis using the command line version. I double-checked the result on the web, and I noticed that the output is quite different using the same input. I also adjust parameters to make both sources comparable. May I ask for your help to understand it?

As output, the command line returned 5 results , but the web only returned 2 results. Also, the results do not match. Am I doing something wrong in parameters adjustments?

Command line 
IntaRNA  -t $file_path -m $other_file_path  -s 5 -p 7 -w 150 -L 100 -o

Web 
![Screen Shot 2024-04-19 at 2 03 12 PM](https://github.com/BackofenLab/IntaRNA/assets/64810030/4e74a29b-0e48-4e6b-833f-9fd3fefe0c9d)

**Comment by martin-raden** [comment]
Hi @paolabc,

thanks for your question and detailed check.

Eventually, given your command line arguments, I guess **you are using the outdated original IntaRNA version 1 !!!!**

You get the recent version either via conda or via manual installation from Github, see [here](https://github.com/BackofenLab/IntaRNA#install)

You can check what version you are using on the command line via
```sh
IntaRNA --version
```
If this is not working, you are definitely using the outdated old version...

The webserver is not running the most recent version but something close, i.e.
```sh
IntaRNA version 3.3.1 linking Vienna RNA package 2.5.0
```

Here the command excuted by the webserver:
```sh
IntaRNA --query=input_query.fa --seedBP=7 --out=pMinE:pairMinE.csv --out=qMinE:QueryMinE.csv --target=input_target.fa --seedMaxE=0 --outOverlap=Q --tAccW=150 --outMaxE=0 --outDeltaE=100 --seedNoGUend --mode=H --qAccW=150 --outNumber=5 --outBestSeedOnly --outMode=C --temperature=37.0 --outNoGUend --outCsvSort=E --energyVRNA=Turner04 --qAccL=100 --outCsvCols=id1,start1,end1,seedStart1,seedEnd1,ED1,id2,start2,end2,seedStart2,seedEnd2,ED2,E,E_hybrid,E_norm,subseqDP,hybridDP,seq1,seq2 --outNoLP --tIdxPos0=1 --out=tMinE:TargetMinE.csv --seedMaxUP=0 --qIdxPos0=1 --seedMinPu=0 --tAccL=100 --out=predictions.sorted.csv
```

Hope that helps! Let me know if you still face issues!

Best,
Martin

**Comment by paolabc** [comment]
Hi

Thank you for your answer. Indeed, I installed the first from conda the first time. And yes,  I got the same result with this parameters.

Thank you!
