### ISSUE TITLE
IntaRNA seedTQ triggers non-complementary base pair error using dot-bar-notation

### ISSUE THREAD

**Issue by Tim15-tech** [BackofenLab/IntaRNA#220]
First, thanks a lot for the program! I am in particular interested in running it with a seed specified via the dot-bar-annotation, so calucalting the energy for a given interaction in the end. However, when running in example:
IntaRNAexact --intLenMax=60 --seedTQ='1|||||||...|||&5|||.|||||||' -t AAACACCCCUGGUUUGG --tRegion=1-13 -q AAACACCCGGUGUUUGG –qRegion=5-15

the error of non-complementary base pairs is raised:

# WARNING : explicit seed '1|||||||...|||&5|||.|||||||' contains non-complementary base pairs and will be ignored

I checked the dot-bar, but it is also according to IntaRNAs output, e.g. via:

IntaRNA --outCsvCols=id1,start1,end1,id2,start2,end2,subseqDP,hybridDB,hybridDBfull,E -t AAACACCCCUGGUUUGG -q AAACACCCGGUGUUUGG --outMode=C
id1;start1;end1;id2;start2;end2;subseqDP;hybridDB;hybridDBfull;E
target;1;13;query;5;15;AAACACCCCUGGU&ACCCGGUGUUU;1|||||||...|||&5|||.|||||||;1|||||||...|||....&1....|||.|||||||..;-6.6

according to the output when called only IntaRNA using the sequences without a seed.

I also simply called IntaRNA --seedTQ='1|||||||...|||&5|||.|||||||' -t AAACACCCCUGGUUUGG -q AAACACCCGGUGUUUGG to erase issues with additional commands, same error.

I haven’t yet found the mistake. Am I calling it wrong? I also tested it with another sequence and ran into the same problem. However, when reading the code I didn’t yet manage to find a mistake in IntaRNA, in particular the SeedHandlerExplicit.cpp, but might have misunderstood something.

(IntaRNA was installed via the conda command in the git-page)

**Comment by martin-raden** [comment]
Hi Tim,

thanks for the bug report and all the details. Given that I could nail down the problem pretty fast.

**Congratulations: you found one of the (hopefully) few bugs in IntaRNA!**

I forgot to reverse the queries dot-bar string, such that the wrong positions are tested for complementarity.. uaks..

I will try to push a bug fix release tomorrow or day after, such that you can continue with your research!

Best,
Martin

**Comment by martin-raden** [comment]
fixed by ab7b22035309cf1f130d0d285170ea5e7220d018

**Comment by martin-raden** [comment]
Hi @Tim15-tech 

bugfix release is out. Will take some hours to get the new release available via bioconda, but most likely available by tomorrow at latest.

Best,
Martin

**Comment by martin-raden** [comment]
ok, conda release is done (should be available soon).

thanks again for the bug report!

Best,
Martin

**Comment by Tim15-tech** [comment]
Thank you so much, both for the bugfixing and in general for the program - very nice written code with a good readability :-)
