### ISSUE TITLE
travis using conda packages

### ISSUE THREAD

**Issue by martin-mann** [BackofenLab/IntaRNA#24]
please adapt the .travis for conda to get VRNA 2.2.10

**Comment by bgruening** [comment]
#26 should solve this. Please note that your autotools setup still does not find boost.

**Comment by martin-mann** [comment]
@bgruening thanks a lot! 
the boost problem was due to a wrong boost path in the configure call (fixed).
the remaining linker problem is due to an enabled LTO-compilation of the conda VRNA package, which clashes with the g++ version we use. Sebastian is already fixing the VRNA build (disabling LTO), such that this should be resolved within the next hours.

**Comment by bgruening** [comment]
This I call a great collaboration!
