### ISSUE TITLE
Comparison to other RNA-RNA interaction prediction methods

### ISSUE THREAD

**Issue by michauhl** [BackofenLab/IntaRNA#30]
Some recent publications with RNA-RNA interaction prediction method comparsions:

An accessibility-incorporated method for accurate prediction of RNA–RNA interactions from sequence data
http://bioinformatics.oxfordjournals.org/content/early/2016/10/07/bioinformatics.btw603.full

A comprehensive comparison of general RNA–RNA interaction prediction methods
http://nar.oxfordjournals.org/content/44/7/e61.short

**Comment by martin-mann** [comment]
Compare with accessfold paper (17 verified interactions)
