### ISSUE TITLE
Interaction input file for defining query RNA - target RNA interaction pairs

### ISSUE THREAD

**Issue by michauhl** [BackofenLab/IntaRNA#32]
This might be helpful if we have larger query / target FASTA files and are only interested in interactions between certain pairs (not the default all vs all). E.g. a simple table with one pair (2 IDs) per line. If BED files are given too, the possible interaction regions between the pairs will get further narrowed down.

**Comment by martin-raden** [comment]
implemented via `--tSet` and `--qSet`
