### ISSUE TITLE
SSE Optimization of IntaRNA

### ISSUE THREAD

**Issue by joachimwolff** [BackofenLab/IntaRNA#47]
IntaRNA is an algorithm for the prediction of RNA-RNA interactions ([Publication](https://www.ncbi.nlm.nih.gov/pubmed/18940824)). Right now a new version of IntaRNA is in development and we want to optimize the C++ source code as good as possible. This includes the usage of modern low level instructions like they are given by SSE. In this student project the IntaRNA source code will be evaluated and optimized with SSE to increase the performance of the algorithm. 

Requirements:
- C++ programming skills
- Knowledge about algorithms & datastructures

For degree: Bachelor thesis / Master project
Supervisor: Martin Mann, Joachim Wolff

**Comment by martin-mann** [comment]
denke das lassen wir dann doch.. :)
