### ISSUE TITLE
test: restrict max helix length

### ISSUE THREAD

**Issue by martin-raden** [BackofenLab/IntaRNA#69]
- alter recursion such that intermolecular helices are restricted to length *k*, ie long helices are interrupted by bulges/intLoops every *k* basepairs
- check RNAstrand data (Andronescu et al, 2006): helices in RNA structures on avg. at most 10 bps! (talk by Juraj Michalik in Bled17)

**Comment by martin-mann** [comment]
assigned to @RickGelhausen

**Comment by martin-raden** [comment]
released in v2.4.0
