### ISSUE TITLE
OS X install instructions with homebrew

### ISSUE THREAD

**Issue by lbarquist** [BackofenLab/IntaRNA#74]
Hi,

It's taken me a few hours and a lot of frustration to get IntaRNA 2.0.2 to build under OS X (Sierra 10.12.4) using homebrew. I thought I'd share how I got it to work in the end, in case you want to include it in your documentation and hopefully save others the headache, as the dependencies require some not completely obvious options:

(need homebrew installed first, obviously)

brew install gcc --without-multilib

(--without-multilib is necessary for OpenMP multithreading support -- note OS X default gcc/clang doesn't support OpenMP, so we need to install standard gcc/g++)

brew install boost --cc=gcc-6

(--cc=gcc-6 is necessary to build boost with standard gcc, rather than the default bottle which appears to have been built with the system clang. Brew installs gcc/g++ as /usr/local/bin/gcc-VERSION by default to avoid clashing with the system gcc/clang. 6 is the current version as of writing, but may change)

brew install viennarna
brew install doxygen

./configure CC=gcc-6 CXX=g++-6

(set up makefiles to use standard gcc/g++ from brew, obviously will need to change to appropriate version if not still 6)

the make, make test, etc. as normal should work. I haven't tested it extensively, but at least make test runs without any problems.

Hope this is useful.

-Lars

**Comment by martin-mann** [comment]
Hi @lbarquist , many many thanks for this contribution! Since I dont have an OSX system at hand, I could not provide such information.

I will add is asap as a new section to the master README!

Thanks,
Martin

**Comment by martin-mann** [comment]
instructions added to the README.md of `intarna-2` branch to be merged into the master branch

**Comment by martin-mann** [comment]
merged to master branch
