### ISSUE TITLE
partition functions for interaction sites

### ISSUE THREAD

**Issue by martin-raden** [BackofenLab/IntaRNA#8]
### compute partition function for interaction sites, to
- [x] predict interaction site with maximal probability O(n^4) space and time
- [ ] predict interaction site with maximal probability O(n^2) space and O(n^4) time
- [ ] enable approximate computation via heuristic version
- [ ] enable seed constraint
- [ ] compute probability of an interaction site

### output
- [ ] compute position-wise probability (per sequence) to be within an interaction site
- [ ] dot-plot of interaction base pair probabilities
- [ ] dot-plot of interaction site probability (per sequence)

**Comment by martin-mann** [comment]
PredictorMaxProb enables 
- partition function computation
- identification of interaction site with maximal probability

**Comment by martin-raden** [comment]
will be part of v3
