### ISSUE TITLE
ViennaRNA SHAPE data support for accessibility handling

### ISSUE THREAD

**Issue by martin-mann** [BackofenLab/IntaRNA#89]
- [x] extend VRNA accessibility handler to support SHAPE data input
- [x] extend interface to support SHAPE data for accesibility computation
  - [x] shape data file (check if file exists if file)
  - [x] shape method (VRNA encoding, check with regex)
  - [x] shape conversion (VRNA encoding, check with regex)
- [x] update README
- [ ] info at Alain

**Comment by martin-mann** [comment]
@mmiladi picking up our emailing from yesterday.. the issue is open since october.. hehe.. maybe we will get something done here!?!

**Comment by mmiladi** [comment]
@martin-mann Oops sorry the email notification was off for here. Can u please point-out to the main source code file needed to be extended?

**Comment by martin-mann** [comment]
mhh... no clear plan so far but VRNA-based accessibilities are computed in `src/IntaRNA/AccessibilityVrna.*`

Currently, all constraints are encoded by `src/IntaRNA/AccessibilityConstraint` so I would suggest to inherit from this class something like `AccessibilityConstraintShape` where the SHAPE-related input is encapsulated. Within `AccessibilityVrna` one can check whether or not the provided constraint is an instance of the new class and act accordingly. I have not checked how to use the VRNA-lib-API to post SHAPE-constraints, but either it is already possible or we can suggest according changes to Ronny for the next release.

Beside changing these two classes, one has to extend `src/bin/CommandLineParsing` in order to add an according parameter (for both query and target) and to fill the `AccessibilityConstraintShape` if needed (including error handling..).

Note, SHAPE data encoding-wise I would suggest to be VRNA conform, since this will ease the usage of the interface.

Think this would be the cleanest solution.

**Comment by mmiladi** [comment]
>Currently, all constraints are encoded by `src/IntaRNA/AccessibilityConstraint` so I would suggest to inherit from this class something like `AccessibilityConstraintShape` where the SHAPE-related input is encapsulated. 

Sounds as a good idea. Does IntaRNA use similar constraint encoding as vrna?

> I have not checked how to use the VRNA-lib-API to post SHAPE-constraints, but either it is already possible or we can suggest according changes to Ronny for the next release.

Since SHAPE is something we wanted to have for LocARNA as well, I would suggest to collect ideas from Ronny and Sebastian as well. This helps to achieve a sustainable interface vrna-lib interface (in case it doesn't exist).

> Beside changing these two classes, one has to extend `src/bin/CommandLineParsing` in order to add an according parameter (for both query and target) and to fill the `AccessibilityConstraintShape` if needed (including error handling..).
Note, SHAPE data encoding-wise I would suggest to be VRNA conform, since this will ease the usage of the interface.

Completely agree. Complying the data and arguments format of RNAfold would makes user life easier :)

**Comment by martin-mann** [comment]
have opened the branch 'shape' that covers the preparation for this incorporation. getting closer to have it ready!

**Comment by mmiladi** [comment]
Wonderful!

**Comment by martin-mann** [comment]
ok, I think most stuff is in and it SHOULD work.. havent tested it yet.

@mmiladi feel free to test whether we get the same results/PU values as with your hacked RNAplfold version. 

I will try to test myself asap. 

As soon as this is tested and confirmed, I will close the issue.

**Comment by martin-mann** [comment]
still buggy, dont try yet.. ;)

**Comment by martin-mann** [comment]
ok, checks and tests fixed.. should work.. :)

**Comment by martin-mann** [comment]
implemented by #113
