### ISSUE TITLE
--seedQT

### ISSUE THREAD

**Issue by mega4** [BackofenLab/IntaRNA#93]
Is that parameter available? IntaRNA cannot find it on the local copy

**Comment by martin-mann** [comment]
uaks.. hi @mega4 that is a typo in the documentation. the correct parameter name is `--seedTQ`

sorry for the confusion. I will change the documenation asap!

thanks for bringing this up!

**Comment by martin-mann** [comment]
solved with caa99f2346cc38fcb2ad4cb48ca80ad631fd42f7

**Comment by mega4** [comment]
Dear Martin. Thank you for a quick response and for an awesome tool.
I am trying to input a line
IntaRNA -t target.fasta -q query.fasta --seedTQ 62||||.||||||&1||||||||||
and get a syntax error.
Is that a right format for encoding known seed?
all the best
George Z

**Comment by martin-mann** [comment]
Hi Georg,

you have to quote the seed coding since '|' character is a shell-specific pipe symbol that gets interpreted by your shell, i.e. run

```[bash]
IntaRNA -t target.fasta -q query.fasta --seedTQ='62||||.||||||&1||||||||||'
```

and it should work fine..  I will update the documentation accordingly!
Best,
Martin

**Comment by mega4** [comment]
Thank you again!
When I input

IntaRNA -t target.fasta -q query.fasta --seedTQ='62||||.||||||&1||||||||||'

I get
 # ERROR : unrecognised option '--seedTQ=62||||.||||||&1||||||||||'

**Comment by martin-mann** [comment]
are you sure that you are using version 2.1.0? please check
```[bash]
IntaRNA --version
```

**Comment by mega4** [comment]
no, it is 2.0.3
I will install a newer one
Thank you!
